name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Inject .env variables
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY }}" >> .env

      - name: Debug environment variables
        run: cat .env # Add this for debugging purposes

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
